school-iems-code/school-iems-SourceCode/EMS.Web.UI/Areas/BasicAccounting/Controllers/BranchController.cs
//File: UI Controller
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EMS.Web.Framework.Bases.Mvc;
using EMS.Framework;
using EMS.Framework.Attributes;
using EMS.DataAccess.Data;
using EMS.Framework.Objects;
using EMS.Framework.Permissions;

namespace EMS.Web.UI.Areas.BasicAccounting.Controllers
{
    /// <summary>
    /// You can add your custom code here.
    /// </summary>
    ///[EmsAuthorize(User_Account.UserAuthorizeTypeEnum.Employee)]
    public class BranchController : EmployeeBaseController
	{
    
        public ActionResult BranchAddEdit()
        {
            /*if (!PermissionUtil.HasPermission(PermissionCollection.BasicAccountingArea.Branch.CanView))
            {
                return RedirectToAction("PermissionDenied", "Home", new { area = "" });
            }*/
            return View();
        }
        public ActionResult BranchList()
        {
            /*if (!PermissionUtil.HasPermission(PermissionCollection.BasicAccountingArea.Branch.CanView))
            {
                return RedirectToAction("PermissionDenied", "Home", new { area = "" });
            }*/
            return View();
        }
	}
}

school-iems-code/school-iems-SourceCode/EMS.Web.UI/Areas/BasicAccounting/Views/Branch/BranchAddEdit.cshtml
<!--File:BAcnt_Branch Add/Edit View-->
@using EMS.DataAccess.Data;
@{
    ViewBag.Title = "BasicAccounting: Add/Edit Branch";
    Layout = "~/Areas/BasicAccounting/Views/Shared/_LayoutBasicAccounting.cshtml";
    // Angular Properties
    var id = Request.QueryString["id"];//ViewContext.RouteData.Values["id"];
    var BranchId = (string) id == null?"0":(string)id;
    
    //BAcnt_Branch WebApi Single Row link   
    var getBranchByIdUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "GetBranchById", area = "BasicAccounting" });
    var getBranchDataExtraUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "GetBranchDataExtra", area = "BasicAccounting" });
    var saveBranchUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "SaveBranch", area = "BasicAccounting" });
    var deleteBranchByIdUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "GetDeleteBranchById", area = "BasicAccounting" });

    //BAcnt_Branch WebApi List link 
    var getPagedBranchUrl = Url.HttpRouteUrl("DefaultApi", new {controller = "BranchApi", action = "GetPagedBranch", area = "BasicAccounting"});
    var getAllBranchUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "GetAllBranch", area = "BasicAccounting" });
    var saveBranchListUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "SaveBranchList", area = "BasicAccounting" });
    var getBranchListDataExtraUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "GetBranchListDataExtra", area = "BasicAccounting" });

    var editBranchByIdPageUrl = Url.Action("BranchAddEdit", "Branch", new { area = "BasicAccounting" });
    var listBranchPageUrl = Url.Action("BranchList", "Branch", new { area = "BasicAccounting" });
    
    //BAcnt_Branch Angular Functions
    string getBranchById="getBranchById";
    var saveBranch = "saveBranch";
    var getNewBranch = "getNewBranch";
    var refreshPage = "loadPage()";
    string deleteBranchById="deleteBranchById";
    string loadBranchExtraData="loadBranchExtraData";
}
@section ScriptSection
{
    <script src="~/Areas/BasicAccounting/Views/Branch/BranchAddEdit.js"></script>
}

<div id="BranchAddEdit" class="row" ng-controller="BranchAddEditCtrl" ng-init="Init(
      '@BranchId'
      ,'@getBranchByIdUrl'
      ,'@getBranchDataExtraUrl'
      ,'@saveBranchUrl'
      ,'@deleteBranchByIdUrl')">
      
    <div class="col-lg-12 col-sm-12 col-xs-12">
     <div ng-Hide="!HasError ||ErrorMsg==''" class="alert alert-danger fade in radius-bordered alert-shadowed">
            <button ng-click="HasError=false" class="close" data-dismiss1="alert">×</button>
            <i class="fa-fw fa fa-warning"></i>
            <strong>Attention Please!</strong> {{ErrorMsg}}
      </div>
      <div ng-show="HasViewPermission">
        <div class="widget" >
            <div class="widget-header bordered-bottom bordered-sky ">
                <i class="widget-icon fa fa-edit bold  "></i>
                <span class="widget-caption ">
                    Add/Edit
                    <strong ng-show="Branch.@BAcnt_Branch.Property_Name!=''">{{(Branch.@BAcnt_Branch.Property_Name)}}</strong>
                </span>
                <div class="widget-buttons buttons-bordered no-padding-right" style="display: none">
                    <span class="input-icon">
                        <input type="text" ng-model="BranchId" ng-Enter="@(getBranchById)()" class="form-control input-xs " id="glyphicon-search" placeholder="Search" >
                        <i class="glyphicon glyphicon-search blue"></i>
                    </span>
                  
                </div>
                <div class="widget-buttons no-padding-left">
                    <button ng-click="@(getNewBranch)()" class="btn btn-success btn-xs"><i class="fa fa-plus"></i> Add New</button>
                    <a href="@(listBranchPageUrl)" class="btn btn-blue btn-xs"><i class="fa fa-arrow-left" target="_blank"></i> Back To List</a>
                    <button ng-click="@refreshPage" class="btn btn-info btn-xs"><i class="fa fa-refresh"></i> Refresh</button>
                </div>
            </div><!--Widget Header end-->
            <div class="widget-body">
                <div class="row">
                  <div class="col-md-6 table-form">
                     <table class="form" width="100%" border="0" cellspacing="2" cellpadding="3">
                        <tbody>
                             <tr>
                                <td class="fieldlabel">Name <span class="red glyphicon glyphicon-asterisk"></span></td>
                                <td class="fieldarea">
                                    <input type="text" ng-model="Branch.@BAcnt_Branch.Property_Name" class="form-control" placeholder="Enter Name" maxlength="255" required="" />
                                </td>
                                <td class="fieldarea-tooltip"><span><i class="fa fa-question-circle" data-title="Enter Name." data-toggle="tooltip"></i></span></td>
                            </tr>
                             <tr>
                                <td class="fieldlabel">Short Name <span class="red glyphicon glyphicon-asterisk"></span></td>
                                <td class="fieldarea">
                                    <input type="text" ng-model="Branch.@BAcnt_Branch.Property_ShortName" class="form-control" placeholder="Enter Short Name" maxlength="50" required="" />
                                </td>
                                <td class="fieldarea-tooltip"><span><i class="fa fa-question-circle" data-title="Enter Short Name." data-toggle="tooltip"></i></span></td>
                            </tr>
                             <tr>
                                <td class="fieldlabel">Code </td>
                                <td class="fieldarea">
                                    <input type="text" ng-model="Branch.@BAcnt_Branch.Property_Code" class="form-control" placeholder="Enter Code" maxlength="50"  />
                                </td>
                                <td class="fieldarea-tooltip"><span><i class="fa fa-question-circle" data-title="Enter Code." data-toggle="tooltip"></i></span></td>
                            </tr>
                             <tr>
                                <td class="fieldlabel">Address <span class="red glyphicon glyphicon-asterisk"></span></td>
                                <td class="fieldarea">
                                    <input type="text" ng-model="Branch.@BAcnt_Branch.Property_Address" class="form-control" placeholder="Enter Address"  required="" />
                                </td>
                                <td class="fieldarea-tooltip"><span><i class="fa fa-question-circle" data-title="Enter Address." data-toggle="tooltip"></i></span></td>
                            </tr>
                             <tr>
                                <td class="fieldlabel">Order No </td>
                                <td class="fieldarea">
                                    <input type="number" ng-model="Branch.@BAcnt_Branch.Property_OrderNo" class="form-control" placeholder="Enter Order No"   />
                                </td>
                                <td class="fieldarea-tooltip"><span><i class="fa fa-question-circle" data-title="Enter Order No." data-toggle="tooltip"></i></span></td>
                            </tr>
                             <tr>
                                <td class="fieldlabel">Is Enable </td>
                                <td class="fieldarea">
                                    <label class="checkbox-inline">
                                    <input type="checkbox" ng-model="Branch.@BAcnt_Branch.Property_IsEnable"  />
                                    </label>
                                </td>
                                <td class="fieldarea-tooltip"><span><i class="fa fa-question-circle" data-title="Check Is Enable if required." data-toggle="tooltip"></i></span></td>
                             </tr>
                        
                             <tr>
                                <td class="fieldlabel">Is Deleted </td>
                                <td class="fieldarea">
                                    <label class="checkbox-inline">
                                    <input type="checkbox" ng-model="Branch.@BAcnt_Branch.Property_IsDeleted"  />
                                    </label>
                                </td>
                                <td class="fieldarea-tooltip"><span><i class="fa fa-question-circle" data-title="Check Is Deleted if required." data-toggle="tooltip"></i></span></td>
                             </tr>
                        
                   
                         <tr>
                            <td class="fieldlabel">Company Account </td>
                            <td class="fieldarea">
                                <select ng-model="Branch.@BAcnt_Branch.Property_CompanyId"
                                        ng-options="option.Id as option.Name for option in CompanyAccountList " ng-init="" class="form-control select-inline">
                                    <option value="" label="" class="">---Select One---</option>
                                </select>
                            </td>
                            <td class="fieldarea-tooltip"><span><i class="fa fa-question-circle" data-title="Select Company Account." data-toggle="tooltip"></i></span></td>
                        </tr>
                  

                            </tbody>
                        </table>
                    </div><!--Col end-->
                </div><!--Row end-->
            </div><!--Widget Body end-->
            <div class="widget-footer text-center">
                <div class="row">
                    <div class="col-md-6 text-center">
                        <button ng-click="@(saveBranch)()" class="btn btn-md btn-success"><span class="fa fa-save"></span> Save</button>
                     </div>
                </div>
            </div>
        </div>
      </div><!--view permission end-->
    </div>
</div><!--controller end-->

school-iems-code/school-iems-SourceCode/EMS.Web.UI/Areas/BasicAccounting/Views/Branch/BranchList.cshtml
<!--File:BAcnt_Branch List View-->
@using EMS.DataAccess.Data;
@{
    ViewBag.Title = "BasicAccounting: Branch List";
    Layout = "~/Areas/BasicAccounting/Views/Shared/_LayoutBasicAccounting.cshtml";
    
    // Angular Properties
    var id = Request.QueryString["id"];//ViewContext.RouteData.Values["id"];
    var BranchId = (string) id == null?"0":(string)id;
    
    //WebApi link for single row 
    var getBranchByIdUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "GetBranchById", area = "BasicAccounting" });
    var getBranchDataExtraUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "GetBranchDataExtra", area = "BasicAccounting" });
    var saveBranchUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "SaveBranch", area = "BasicAccounting" });
    var deleteBranchByIdUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "GetDeleteBranchById", area = "BasicAccounting" });

    //WebApi link for List
    var getPagedBranchUrl = Url.HttpRouteUrl("DefaultApi", new {controller = "BranchApi", action = "GetPagedBranch", area = "BasicAccounting"});
    var getAllBranchUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "GetAllBranch", area = "BasicAccounting" });
    var saveBranchListUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "SaveBranchList", area = "BasicAccounting" });
    var getBranchListDataExtraUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "BranchApi", action = "GetBranchListDataExtra", area = "BasicAccounting" });

    var editBranchByIdPageUrl = Url.Action("BranchAddEdit", "Branch", new { area = "BasicAccounting" });

    //Angular Function Name
    var getNewBranch = "getNewBranch";
    var saveBranch = "saveBranch";
    var deleteBranchById = "deleteBranchById";
    var deleteBranchByObj = "deleteBranchByObj";
    //for list
    var searchBranchList = "searchBranchList";
    var getPagedBranchList = "getPagedBranchList";
    var getAllBranchList = "getAllBranchList";
    var saveBranchList = "saveBranchList";
    var getBranchListExtraData = "getBranchListExtraData";

    var refreshPage = "loadPage()";
    
}
@section ScriptSection
{
    <script src="~/Areas/BasicAccounting/Views/Branch/BranchList.js"></script>
}


<div ng-controller="BranchListCtrl"
     ng-init="Init(
      '@getPagedBranchUrl'
     ,'@deleteBranchByIdUrl'
     ,'@getBranchListDataExtraUrl'
     ,'@saveBranchListUrl'
     ,'@getBranchByIdUrl'
     ,'@getBranchDataExtraUrl'
     ,'@saveBranchUrl'
     )">
     <div ng-Hide="!HasError ||ErrorMsg==''" class="alert alert-danger fade in radius-bordered alert-shadowed">
            <button ng-click="HasError=false" class="close" data-dismiss1="alert">×</button>
            <i class="fa-fw fa fa-warning"></i>
            <strong>Attention Please!</strong> {{ErrorMsg}}
     </div>
    <div class="widget" ng-show="HasViewPermission">

        <div class="widget-header bordered-bottom bordered-sky ">
            <i class="widget-icon fa fa-list bold  "></i>
            <span class="widget-caption ">Manage Branch </span>
              <div class="widget-buttons buttons-bordered no-padding-right" style="display:none">
                <span class="widget-caption form-inline">
                    @*<span>Select Company</span>*@
                     <select ng-model="SelectedCompanyId" ng-change="@(searchBranchList)()" 
                        ng-options="option.Id as option.Name for option in CompanyAccountList " ng-init="" class="form-control input-xs ">
                        <option value="" label="" class="">---Select All Company---</option>
                     </select>
                </span>
              </div>       
            <div class="widget-buttons buttons-bordered no-padding-right">
                <span class="input-icon">
                    <input type="text" ng-model="SearchText" ng-Enter="@(searchBranchList)()" class="form-control input-xs " id="glyphicon-search" placeholder="Search" style="">
                    <i class="glyphicon glyphicon-search blue"></i>
                </span>
            </div>
            <div class="widget-buttons no-padding-left">
                <a target="_blank" href="@editBranchByIdPageUrl?id=0" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> Add New</a>
                <button ng-click="@(searchBranchList)()" class="btn btn-info btn-xs"><i class="fa fa-refresh"></i> Refresh</button>
            </div>
        </div>
        <div class="widget-body no-padding"  style="overflow:auto">
            <div class="table-footer no-print">
                @OptionControl()
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead class="bordered-blue">
                <tr>
                    <th class="text-center" style="display:none">
                        <input type="checkbox" ng-click="selectAll($event)">
                    </th>
                    <th class="text-center">SN</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Short Name</th>
                    <th class="text-center">Code</th>
                    <th class="text-center">Address</th>
                    <th class="text-center">Order No</th>
                    <th class="text-center">Is Enable</th>
                    <th class="text-center">Is Deleted</th>
                    <!--th class="text-center">Company Id</th-->
                    <th class="text-center no-print">Action</th>
                </tr>
                </thead>
                <tbody>
    
                <tr ng-repeat="row in BranchList">
                    <td class="text-center" style="display:none">
                        <input type="checkbox" ng-model="row.@BAcnt_Branch.Property_IsSelected" /> 
                    </td>
                    <td class="text-center">{{$index+1}}</td>
                    <td class="">{{row.@BAcnt_Branch.Property_Name}}</td>
                    <td class="">{{row.@BAcnt_Branch.Property_ShortName}}</td>
                    <td class="">{{row.@BAcnt_Branch.Property_Code}}</td>
                    <td class="">{{row.@BAcnt_Branch.Property_Address}}</td>
                    <td class="">{{row.@BAcnt_Branch.Property_OrderNo}}</td>
                    <td class="">{{row.@BAcnt_Branch.Property_IsEnable}}</td>
                    <td class="">{{row.@BAcnt_Branch.Property_IsDeleted}}</td>
                    <!--td class="">{{row.@BAcnt_Branch.Property_CompanyId}}</td-->
                    <td class="text-center no-print">
                        <a target="_blank" href="@(editBranchByIdPageUrl)/?id={{row.Id}}" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i> Edit</a>
                        <button ng-click="@(deleteBranchById)(row)" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></button>
                     
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="table-footer no-print">
                @OptionControl()
            </div>
        </div>
    </div>
</div>

@helper  OptionControl()
{
    <div class="row no-print">
        <div class="col-sm-12">
            <div class="form-inline pull-left">
                <div class="form-group">
                    <label ng-hide="totalServerItems==0">Showing {{totalServerItems*(PageNo-1)+1}} to {{totalServerItems*PageNo}} of {{totalItems}} </label>
                    <label ng-show="totalServerItems==0" class="text-danger">No Data Found!</label>
                </div>
            </div>
            <div class="form-inline pull-right">
                <div class="form-group">
                    <label>Page Size</label>
                    <input ng-model="PageSize" ng-enter="changePageSize()" class="form-control input-opt" autocomplete="on" placeholder="Page Size" type="number" min="1">
                </div>
                <div class="form-group">
                    <label>Page No.</label>
                    <input ng-model="PageNo" ng-enter="changePageNo()" class="form-control input-opt" autocomplete="on" placeholder="Page No" type="number" min="1">
                    <label>of {{totalItems/PageSize| number:0}}</label>
                </div>
                <div class="form-group">
                    <button ng-click="prev()" ng-hide="totalItems == 0 || PageNo <= 1" class="btn btn-info btn-opt" type="button"><i class="fa fa-angle-double-left"></i>Previous&nbsp;</button>
                    <button ng-click="next()" ng-hide="totalItems == 0 || PageNo >= totalPage" class="btn btn-info btn-opt" type="button">&nbsp;Next&nbsp;<i class="fa fa-angle-double-right"></i></button>
                </div>
            </div>
        </div>
    </div>
}