school-iems-code/school-iems-SourceCode/EMS.Web.UI/Areas/HR/Controllers/ReportController.cs
//File: UI Controller
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EMS.Web.Framework.Bases;
using EMS.Framework;
using EMS.Framework.Attributes;
using EMS.DataAccess.Data;
using EMS.Framework.Objects;
using EMS.Framework.Permissions;
using EMS.Framework.Utils;
using EMS.Web.Framework.Bases.Mvc;
using EMS.Web.Jsons.Models;

namespace EMS.Web.UI.Areas.HR.Controllers
{
    /// <summary>
    /// You can add your custom code here.
    /// </summary>

    public class ReportController : EmployeeBaseController
    {

        public ActionResult MonthlySalarySummary()
        {
            if (!PermissionUtil.HasPermission(PermissionCollection.HumanResourceArea.Reports.CanViewMonthlySalarySummaryReport))
            {
                return RedirectToAction("PermissionDenied", "Home", new { area = "" });
            }
            return View();
        }
        public ActionResult YearlySalarySummary()
        {
            if (!PermissionUtil.HasPermission(PermissionCollection.HumanResourceArea.Reports.CanViewYearlySalarySummaryReport))
            {
                return RedirectToAction("PermissionDenied", "Home", new { area = "" });
            }
            return View();
        }
        public ActionResult MonthlySalaryDetails()
        {
            if (!PermissionUtil.HasPermission(PermissionCollection.HumanResourceArea.Reports.CanViewMonthlySalaryDetailsReport))
            {
                return RedirectToAction("PermissionDenied", "Home", new { area = "" });
            }
            return View();
        }

        public ActionResult MonthlySalaryReportWithBankDetails()
        {
            if (!PermissionUtil.HasPermission(PermissionCollection.HumanResourceArea.Reports.CanViewMonthlySalaryWithBankDetails))
            {
                return RedirectToAction("PermissionDenied", "Home", new { area = "" });
            }
            return View();
        }


        #region Monthly Salary Print Json

        public class MonthlySalaryPrintJson
        {
            public int EmployeeId { get; set; }
            public int UserId { get; set; }
            public string EmployeeName { get; set; }
            public string PayrollName { get; set; }
            public string Designation { get; set; }
            public string Remarks { get; set; }
            public List<HR_MonthlyPayslipDetailsJson> MonthlyPayslipDetailsList { get; set; }

            public MonthlySalaryPrintJson()
            {
                MonthlyPayslipDetailsList = new List<HR_MonthlyPayslipDetailsJson>();
            }
        }

        #endregion
        public ActionResult MonthlySalaryPrint(int id=0,int employeeId=0)
        {
            var result = new MvcModelResult<MonthlySalaryPrintJson>();
            if (id <= 0)
            {
                result.HasError = true;
                result.Errors.Add("Please Select a Valid Monthly Salary");
                return View(result);
            }

            if (employeeId <= 0)
            {
                result.HasError = true;
                result.Errors.Add("Select a Valid Employee");
                return View(result);
            }
            var employee = DbInstance.User_Employee
                .Include(x=>x.User_Account)
                .Include(x=>x.HR_Department)
                .Include(x=>x.HR_Position)
                .FirstOrDefault(x => x.Id == employeeId);
            if (employee == null)
            {
                result.HasError = true;
                result.Errors.Add("Employee Not Found.");
                return View(result);
            }
            result.Data = new MonthlySalaryPrintJson();

            result.Data.EmployeeName = employee.User_Account.FullName;
            result.Data.UserId = employee.UserId;
            result.Data.EmployeeId = employee.Id;
            result.Data.Designation = employee.HR_Position.Name + "(" +employee.HR_Department.ShortName+ ")";

            var monthlyPayslip = DbInstance.HR_MonthlyPayslip
                .Include(x=>x.HR_MonthlyPayslipDetails)
                .Include(x=>x.HR_Payroll)
                .FirstOrDefault(q => q.Id == id);

            if (monthlyPayslip == null)
            {
                result.HasError = true;
                result.Errors.Add("Monthly Payslip Not Found.");
                return View(result);
            }

            var payslipDetails = monthlyPayslip.HR_MonthlyPayslipDetails;
            var jsons = new List<HR_MonthlyPayslipDetailsJson>();
            payslipDetails.Map(jsons);

            result.Data.PayrollName = monthlyPayslip.HR_Payroll.Month.ToString() +", "+monthlyPayslip.HR_Payroll.Year;
            result.Data.Remarks = monthlyPayslip.Remarks;

            result.DataBag.TotalAddition = jsons.Where(x => x.IsAddition).Sum(x => x.Value);
            result.DataBag.TotalDeduction = jsons.Where(x => !x.IsAddition).Sum(x => x.Value);

            result.Data.MonthlyPayslipDetailsList = jsons;

            return View(result);

        }
    }
}

school-iems-code/school-iems-SourceCode/EMS.Web.UI/Areas/Inventory/Controllers/ProductCategoryDetailsController.cs
//File: UI Controller
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EMS.Web.Framework.Bases.Mvc;
using EMS.Framework;
using EMS.Framework.Attributes;
using EMS.DataAccess.Data;
using EMS.Framework.Objects;
using EMS.Framework.Permissions;

namespace EMS.Web.UI.Areas.Inventory.Controllers
{
    /// <summary>
    /// You can add your custom code here.
    /// </summary>
    ///[EmsAuthorize(User_Account.UserAuthorizeTypeEnum.Employee)]
    public class ProductCategoryDetailsController : EmployeeBaseController
	{
    
        public ActionResult ProductCategoryDetailsAddEdit()
        {
            /*if (!PermissionUtil.HasPermission(PermissionCollection.InventoryArea.ProductCategoryDetails.CanView))
            {
                return RedirectToAction("PermissionDenied", "Home", new { area = "" });
            }*/
            return View();
        }
        public ActionResult ProductCategoryDetailsList()
        {
            /*if (!PermissionUtil.HasPermission(PermissionCollection.InventoryArea.ProductCategoryDetails.CanView))
            {
                return RedirectToAction("PermissionDenied", "Home", new { area = "" });
            }*/
            return View();
        }
	}
}

school-iems-code/school-iems-SourceCode/EMS.Web.UI/Areas/Inventory/Controllers/ProductCategoryManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc;
using EMS.Web.Framework.Bases.Mvc;


namespace EMS.Web.UI.Areas.Inventory.Controllers
{
    public class ProductCategoryManagerController : EmployeeBaseController
    {
        // GET: Inventory/ProductCardManager
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductCategoryAddEdit()
        {
            return View();
        }
        public ActionResult ProductCategoryList()
        {
            /*if (!PermissionUtil.HasPermission(PermissionCollection.BasicAccountingArea.Voucher.CanView))
            {
                return RedirectToAction("PermissionDenied", "Home", new { area = "" });
            }*/
            return View();
        }
        public ActionResult ProductCategoryDetail()
        {
            /*if (!PermissionUtil.HasPermission(PermissionCollection.BasicAccountingArea.Voucher.CanView))
            {
                return RedirectToAction("PermissionDenied", "Home", new { area = "" });
            }*/
            return View();
        }

        




    }
}

school-iems-code/school-iems-SourceCode/EMS.Web.UI/Areas/Inventory/Views/ProductCategoryManager/ProductCategoryDetail.cshtml
@using EMS.DataAccess.Data;
@{
    ViewBag.Title = "Product Information: Detail";

    // Angular Properties
    var id = Request.QueryString["id"];//ViewContext.RouteData.Values["id"];
    var PurchaseId = (string)id == null ? "0" : (string)id;

    //ProductCardManager WebApi Single Row link
    var getProductCardDetailUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "ProductCardManagerApi", action = "GetProductCardDetail", area = "Inventory" });
    var getPurchaseDetailDataExtraUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "ProductCardManagerApi", action = "GetPurchaseDetailListDataExtra", area = "Inventory" });

    //
    var searchPurchaseDetailList = "searchPurchaseDetailList";

}

@section ScriptSection
{
    <script src="~/Areas/Inventory/Views/ProductCategoryManager/ProductCategoryDetail.js"></script>
}

<div class="page-body">
    <!--File:ProductCardDetail-->
    <div id="ProductCardDetail" class="row ng-scope" ng-controller="ProductCategoryDetailCtrl" ng-init="Init(
       '@getProductCardDetailUrl'
      ,'@getPurchaseDetailDataExtraUrl'
     );">


        <div ng-Hide="!HasError ||ErrorMsg==''" class="alert alert-danger fade in radius-bordered alert-shadowed">
            <button ng-click="HasError=false" class="close" data-dismiss1="alert">×</button>
            <i class="fa-fw fa fa-warning"></i>
            <strong>Attention Please!</strong> {{ErrorMsg}}
        </div>
        <div class="widget" ng-show="HasViewPermission">

            <div class="widget-header bordered-bottom bordered-sky ">
                <i class="widget-icon fa fa-list bold  "></i>
                <span class="widget-caption ">Manage Product</span>
                <div class="widget-buttons buttons-bordered no-padding-right">
                    <span class="widget-caption form-inline">
                        <span>Select Item</span>
                        <select ng-model="SelectedItemId" ng-change="@(searchPurchaseDetailList)()"
                                ng-options="option.Id as option.Name for option in ItemList " ng-init="" class="form-control input-xs ">
                            <option value="" label="" class="">---Select Item---</option>
                        </select>
                    </span>
                </div>
                <div class="widget-buttons buttons-bordered no-padding-right">
                    <span class="widget-caption form-inline">
                        <span>Select Warhouse</span>
                        <select ng-model="SelectedWarhouseId" ng-change="@(searchPurchaseDetailList)()"
                                ng-options="option.Id as option.Name for option in WarhouseList " ng-init="" class="form-control input-xs ">
                            <option value="" label="" class="">---Select Warhouse---</option>
                        </select>
                    </span>
                </div>
                @*<div class="widget-buttons buttons-bordered no-padding-right">
                    <span class="widget-caption form-inline">
                        <span>Select Supplier</span>
                        <select ng-model="SelectedSupplierId" ng-change="@(searchPurchaseDetailList)()"
                                ng-options="option.Id as option.Name for option in SupplierList " ng-init="" class="form-control input-xs ">
                            <option value="" label="" class="">---Select Supplier---</option>
                        </select>
                    </span>
                </div>*@
                

                <div class="widget-buttons buttons-bordered no-padding-right">
                    <span class="input-icon">
                        <input type="text" ng-model="SearchText" ng-Enter="@(searchPurchaseDetailList)()" class="form-control input-xs " id="glyphicon-search" placeholder="Search By Batch No" style="">
                        <i class="glyphicon glyphicon-search blue"></i>
                    </span>
                </div>
                @*<div class="widget-buttons no-padding-left">
                    <a target="_blank" href="" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> Add New</a>
                    <button ng-click="" class="btn btn-info btn-xs"><i class="fa fa-refresh"></i> Refresh</button>
                </div>*@
                
                
               
            </div>
            <div class="widget-header bordered-bottom bordered-sky ">
                <div class="widget-buttons buttons-bordered no-padding-right">
                    <span class="input-icon">
                        <input type="text" ng-model="SelectedFormDate" ng-Enter="@(searchPurchaseDetailList)()" class="form-control input-xs date-picker" id="glyphicon-search" placeholder="Form Date" style="">
                    </span>
                </div>
                <div class="widget-buttons buttons-bordered no-padding-right">
                    <span class="input-icon">
                        <input type="text" ng-model="SelectedToDate" ng-Enter="@(searchPurchaseDetailList)()" class="form-control input-xs date-picker" id="glyphicon-search" placeholder="To Date" style="">
                    </span>
                </div>
            </div>
            
            

            <div class="widget-body no-padding" style="overflow:auto">
                <div class="table-footer no-print">
                    @OptionControl()
                </div>
                <table class="table table-striped table-bordered table-hover">
                    <thead class="bordered-blue">
                        <tr>
                            <th class="text-center" style="display:none">
                                <input type="checkbox" ng-click="selectAll($event)">
                            </th>
                            <th class="text-center">SN</th>
                            <th class="text-center">Item Name</th>
                            <th class="text-center">Batch No</th>
                            <th class="text-center">Store Name</th>
                            @*<th class="text-center">Unit</th>*@
                            <th class="text-center">Unit Type</th>
                            <th class="text-center">Amount</th>
                            <th class="text-center no-print">Action</th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr ng-repeat="row in ProductDetail">
                            <td class="text-center" style="display:none">
                                <input type="checkbox" ng-model="row.@Invt_Item.Property_IsSelected" />
                            </td>
                            <td class="text-center">{{$index+1}}</td>
                            <td class="">{{row.Invt_ItemJson.Name}}</td>
                            <td class="">{{row.BatchNo}}</td>
                            <td class="">{{row.Invt_WarhouseJson.Name}}</td>
                            @*<td class="">{{row.Unit}}</td>*@
                            <td class="">{{row.Invt_ItemJson.UnitType}}</td>
                            <td class="">{{row.Amount}}</td>

                            <td class="text-center no-print">
                                <a target="_blank" href="" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i> Edit</a>
                                <button ng-click="" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></button>

                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="table-footer no-print">
                    @OptionControl()
                </div>
            </div>
        </div>


        @helper  OptionControl()
        {
            <div class="row no-print">
                <div class="col-sm-12">
                    <div class="form-inline pull-left">
                        <div class="form-group">
                            <label ng-hide="totalServerItems==0">Showing {{totalServerItems*(PageNo-1)+1}} to {{totalServerItems*PageNo}} of {{totalItems}} </label>
                            <label ng-show="totalServerItems==0" class="text-danger">No Data Found!</label>
                        </div>
                    </div>
                    <div class="form-inline pull-right">
                        <div class="form-group">
                            <label>Page Size</label>
                            <input ng-model="PageSize" ng-enter="changePageSize()" class="form-control input-opt" autocomplete="on" placeholder="Page Size" type="number" min="1">
                        </div>
                        <div class="form-group">
                            <label>Page No.</label>
                            <input ng-model="PageNo" ng-enter="changePageNo()" class="form-control input-opt" autocomplete="on" placeholder="Page No" type="number" min="1">
                            <label>of {{totalItems/PageSize| number:0}}</label>
                        </div>
                        <div class="form-group">
                            <button ng-click="prev()" ng-hide="totalItems == 0 || PageNo <= 1" class="btn btn-info btn-opt" type="button"><i class="fa fa-angle-double-left"></i>Previous&nbsp;</button>
                            <button ng-click="next()" ng-hide="totalItems == 0 || PageNo >= totalPage" class="btn btn-info btn-opt" type="button">&nbsp;Next&nbsp;<i class="fa fa-angle-double-right"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        }



    </div><!--controller end-->


    <style>

        .voucher-entry-form input,
        .voucher-entry-form optgroup,
        .voucher-entry-form select,
        .voucher-entry-form textarea {
            height: 25px !important;
            font-size: 12px;
        }

        .text-dropdown-toggle .dropdown-menu li a:hover {
            background: #1884e6;
            color: #fff;
        }

        .text-dropdown {
            max-height: 115px;
            overflow-y: auto;
            font-size: 13px;
            padding: 6px 12px;
            width: 100%;
            line-height: 1.42857143;
            background-image: none;
        }

        .text-dropdown-toggle ul {
            max-height: 115px !important;
            padding: 0px !important;
            overflow-x: hidden !important;
        }

            .text-dropdown-toggle ul li a {
                padding-left: 0px !important;
                padding-right: 0px !important;
                padding: 2px 10px !important;
            }
    </style>





</div>

school-iems-code/school-iems-SourceCode/EMS.Web.UI/Areas/Inventory/Views/ProductCategoryManager/ProductCategoryList.cshtml
<!--File:Inv_ProductCategory List View-->
@using EMS.DataAccess.Data;
@{
    ViewBag.Title = "Inventory: Product Category List";
    Layout = "~/Areas/Inventory/Views/Shared/_LayoutInventory.cshtml";

    // Angular Properties
    var id = Request.QueryString["id"];//ViewContext.RouteData.Values["id"];
    var ProductCategoryId = (string)id == null ? "0" : (string)id;

    //WebApi link for single row
    var getProductCategoryByIdUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "ProductCategoryApi", action = "GetProductCategoryById", area = "Inventory" });
    var getProductCategoryDataExtraUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "ProductCategoryApi", action = "GetProductCategoryDataExtra", area = "Inventory" });
    var saveProductCategoryUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "ProductCategoryApi", action = "SaveProductCategory", area = "Inventory" });
    var deleteProductCategoryByIdUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "ProductCategoryManagerApi", action = "GetDeleteProductById", area = "Inventory" });



    var printProductCategoryById = Url.Action("ProductCategoryPrint", "Report", new { area = "BasicAccounting" });


    //WebApi link for List
    var getPagedProductCategoryUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "ProductCategoryManagerApi", action = "GetPagedProductCategory", area = "Inventory" });
    var getAllProductCategoryUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "ProductCategoryApi", action = "GetAllProductCategory", area = "Inventory" });
    var saveProductCategoryListUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "ProductCategoryApi", action = "SaveProductCategoryList", area = "Inventory" });
    var getProductCategoryListDataExtraUrl = Url.HttpRouteUrl("DefaultApi", new { controller = "ProductCategoryApi", action = "GetProductCategoryListDataExtra", area = "Inventory" });

    var editProductCategoryByIdPageUrl = Url.Action("ProductCategoryAddEdit", "ProductCategoryManager", new { area = "Inventory" });

    //Angular Function Name
    var getNewProductCategory = "getNewProductCategory";
    var saveProductCategory = "saveProductCategory";
    var deleteProductCategoryById = "deleteProductCategoryById";
    var deleteProductCategoryByObj = "deleteProductCategoryByObj";
    //for list
    var searchProductCategoryList = "searchProductCategoryList";
    var getPagedProductCategoryList = "getPagedProductCategoryList";
    var getAllProductCategoryList = "getAllProductCategoryList";
    var saveProductCategoryList = "saveProductCategoryList";
    var getProductCategoryListExtraData = "getProductCategoryListExtraData";

    var refreshPage = "loadPage()";

}
@section ScriptSection
{
    <script src="~/Areas/Inventory/Views/ProductCategory/ProductCategoryList.js"></script>
}


<div ng-controller="ProductCategoryListCtrl"
     ng-init="Init(
      '@getPagedProductCategoryUrl'
     ,'@deleteProductCategoryByIdUrl'
     ,'@getProductCategoryListDataExtraUrl'
     ,'@saveProductCategoryListUrl'
     ,'@getProductCategoryByIdUrl'
     ,'@getProductCategoryDataExtraUrl'
     ,'@saveProductCategoryUrl'
     )">
    <div ng-Hide="!HasError ||ErrorMsg==''" class="alert alert-danger fade in radius-bordered alert-shadowed">
        <button ng-click="HasError=false" class="close" data-dismiss1="alert">×</button>
        <i class="fa-fw fa fa-warning"></i>
        <strong>Attention Please!</strong> {{ErrorMsg}}
    </div>
    <div class="widget" ng-show="HasViewPermission">

        <div class="widget-header bordered-bottom bordered-sky ">
            <i class="widget-icon fa fa-list bold  "></i>
            <span class="widget-caption ">Manage Product Category </span>
            <div class="widget-buttons buttons-bordered no-padding-right">
                <span class="input-icon">
                    <input type="text" ng-model="SearchText" ng-Enter="@(searchProductCategoryList)()" class="form-control input-xs " id="glyphicon-search" placeholder="Search" style="">
                    <i class="glyphicon glyphicon-search blue"></i>
                </span>
            </div>
            <div class="widget-buttons no-padding-left">
                <a target="_blank" href="@editProductCategoryByIdPageUrl?id=0" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> Add New</a>
                <button ng-click="@(searchProductCategoryList)()" class="btn btn-info btn-xs"><i class="fa fa-refresh"></i> Refresh</button>
            </div>
        </div>
        <div class="widget-body no-padding" style="overflow:auto">
            <div class="table-footer no-print">
                @OptionControl()
            </div>
            <table class="table table-striped table-bordered table-hover">
                <thead class="bordered-blue">
                    <tr>
                        <th class="text-center" style="display:none">
                            <input type="checkbox" ng-click="selectAll($event)">
                        </th>
                        <th class="text-center">SN</th>
                        <th class="text-center">Title</th>
                        @*<th class="text-center">Parent Id</th>*@
                        @*<th class="text-center">Description</th>*@
                        <!--th class="text-center">Asset Type Enum Id</th-->
                        <th class="text-center">Asset Type</th>
                        <th class="text-center">Name</th>
                        <th class="text-center">ProductCode </th>
                        <th class="text-center">IsBarCoded </th>
                        <th class="text-center">DefaultStoreId </th>
                        <th class="text-center">UnitTypeEnumId </th>
                        <th class="text-center">Sub Title </th>
                        <th class="text-center">Category Unit EnumId </th>
                        <th class="text-center">Category Type EnumId  </th>
                        <th class="text-center">Barcode Type EnumId  </th>
                        <th class="text-center">Warning Quantity </th>
                        <th class="text-center">Remark </th>
                        <th class="text-center">Parent Category Id </th>
                        <th class="text-center">StoreId </th>


                        @*<th class="text-center">Is Deleted</th>*@
                        <th class="text-center no-print">Action</th>
                    </tr>
                </thead>
                <tbody>

                    <tr ng-repeat="row in ProductCategoryList">
                        <td class="text-center" style="display:none">
                            <input type="checkbox" ng-model="row.@Inv_ProductCategory.Property_IsSelected" />
                        </td>
                        <td class="text-center">{{$index+1}}</td>
                        <td class="">{{row.@Inv_ProductCategory.Property_Title}}</td>
                        @*<td class="">{{row.@Inv_ProductCategory.Property_ParentId}}</td>*@
                        @*<td class="">{{row.@Inv_ProductCategory.Property_Description}}</td>*@
                        <!--td class="">{{row.@Inv_ProductCategory.Property_AssetTypeEnumId}}</td-->
                        <td class="">{{row.@Inv_ProductCategory.Property_AssetType}}</td>

                        <td class="">{{row.@Inv_ProductCategory.Property_Name}}</td>
                        <td class="">{{row.@Inv_ProductCategory.Property_ProductCode}}</td>
                        <td class="">{{row.@Inv_ProductCategory.Property_IsBarCoded}}</td>
                        <td class="">{{row.@Inv_ProductCategory.Property_DefaultStoreId}}</td>
                        <td class="">{{row.@Inv_ProductCategory.Property_UnitTypeEnumId}}</td>
                        <td class="">{{row.@Inv_ProductCategory.Property_SubTitle}}</td>
                        <td class="">{{row.@Inv_ProductCategory.Property_CategoryUnitEnumId}}</td>
                        <td class="">{{row.@Inv_ProductCategory.Property_CategoryTypeEnumId}}</td>
                        <td class="">{{row.@Inv_ProductCategory.Property_BarcodeTypeEnumId}}</td>
                        <td class="">{{row.@Inv_ProductCategory.Property_WarningQuantity}}</td>
                        <td class="">{{row.@Inv_ProductCategory.Property_Remark}}</td>
                        <td class="">{{row.@Inv_ProductCategory.Property_ParentCategoryId}}</td>
                        <td class="">{{row.@Inv_ProductCategory.Property_StoreId}}</td>


                        @*<td class="">{{row.@Inv_ProductCategory.Property_IsDeleted}}</td>*@
                        <td class="text-center no-print">
                            <a target="_blank" href="@(editProductCategoryByIdPageUrl)/?id={{row.Id}}" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i> Edit</a>
                            <button ng-click="@(deleteProductCategoryById)(row)" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></button>
                            <a target="_blank" href="@(printProductCategoryById)/?id={{row.Id}}" class="btn btn-xs btn-primary"><i class="fa fa-print"></i> Print</a>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="table-footer no-print">
                @OptionControl()
            </div>
        </div>
    </div>
</div>

@helper  OptionControl()
{
    <div class="row no-print">
        <div class="col-sm-12">
            <div class="form-inline pull-left">
                <div class="form-group">
                    <label ng-hide="totalServerItems==0">Showing {{totalServerItems*(PageNo-1)+1}} to {{totalServerItems*PageNo}} of {{totalItems}} </label>
                    <label ng-show="totalServerItems==0" class="text-danger">No Data Found!</label>
                </div>
            </div>
            <div class="form-inline pull-right">
                <div class="form-group">
                    <label>Page Size</label>
                    <input ng-model="PageSize" ng-enter="changePageSize()" class="form-control input-opt" autocomplete="on" placeholder="Page Size" type="number" min="1">
                </div>
                <div class="form-group">
                    <label>Page No.</label>
                    <input ng-model="PageNo" ng-enter="changePageNo()" class="form-control input-opt" autocomplete="on" placeholder="Page No" type="number" min="1">
                    <label>of {{totalItems/PageSize| number:0}}</label>
                </div>
                <div class="form-group">
                    <button ng-click="prev()" ng-hide="totalItems == 0 || PageNo <= 1" class="btn btn-info btn-opt" type="button"><i class="fa fa-angle-double-left"></i>Previous&nbsp;</button>
                    <button ng-click="next()" ng-hide="totalItems == 0 || PageNo >= totalPage" class="btn btn-info btn-opt" type="button">&nbsp;Next&nbsp;<i class="fa fa-angle-double-right"></i></button>
                </div>
            </div>
        </div>
    </div>
}